drop table if exists users CASCADE;
create table users
(
    id bigint generated by default as identity,
    name varchar(255),
    email varchar(255),

    primary key (id)
);

create table posts
(
    post_id BIGINT, AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT,
    content VARCHAR(1000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
)